# Generated by Django 5.2.4 on 2025-11-07 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('ACTIVO', 'Activo'), ('PASIVO', 'Pasivo'), ('PATRIMONIO', 'Patrimonio'), ('INGRESO', 'Ingreso'), ('COSTO', 'Costo'), ('GASTO', 'Gasto')], max_length=20)),
                ('nivel', models.IntegerField(default=1)),
                ('es_total', models.BooleanField(default=False)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DicksonStatistics.cuentacontable')),
            ],
            options={
                'verbose_name': 'Cuenta Contable',
                'verbose_name_plural': 'Cuentas Contables',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ruc', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='PeriodoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('es_actual', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DicksonStatistics.empresa')),
            ],
            options={
                'verbose_name': 'Periodo Contable',
                'verbose_name_plural': 'Periodos Contables',
                'unique_together': {('empresa', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='EstadoResultados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('orden', models.IntegerField(default=0)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DicksonStatistics.cuentacontable')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DicksonStatistics.periodocontable')),
            ],
            options={
                'verbose_name': 'Estado de Resultados',
                'verbose_name_plural': 'Estados de Resultados',
                'unique_together': {('periodo', 'cuenta')},
            },
        ),
        migrations.CreateModel(
            name='BalanceGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('orden', models.IntegerField(default=0)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DicksonStatistics.cuentacontable')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DicksonStatistics.periodocontable')),
            ],
            options={
                'verbose_name': 'Balance General',
                'verbose_name_plural': 'Balances Generales',
                'unique_together': {('periodo', 'cuenta')},
            },
        ),
        migrations.CreateModel(
            name='AnalisisVertical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_absoluto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('porcentaje', models.DecimalField(decimal_places=4, max_digits=8)),
                ('tipo_estado', models.CharField(choices=[('BALANCE', 'Balance'), ('RESULTADOS', 'Resultados')], max_length=20)),
                ('fecha_calculo', models.DateTimeField(auto_now=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DicksonStatistics.cuentacontable')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DicksonStatistics.periodocontable')),
            ],
            options={
                'verbose_name': 'Análisis Vertical',
                'verbose_name_plural': 'Análisis Verticales',
                'unique_together': {('periodo', 'cuenta', 'tipo_estado')},
            },
        ),
    ]
