# Generated by Django 5.2.4 on 2025-11-24 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DicksonStatistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisHorizontal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_periodo_base', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_periodo_comparativo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('variacion_absoluta', models.DecimalField(decimal_places=2, max_digits=15)),
                ('variacion_porcentual', models.DecimalField(decimal_places=4, max_digits=8)),
                ('tipo_estado', models.CharField(choices=[('BALANCE', 'Balance'), ('RESULTADOS', 'Resultados')], max_length=20)),
                ('fecha_calculo', models.DateTimeField(auto_now=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DicksonStatistics.cuentacontable')),
            ],
            options={
                'verbose_name': 'Análisis Horizontal',
                'verbose_name_plural': 'Análisis Horizontales',
                'unique_together': {('cuenta', 'tipo_estado')},
            },
        ),
    ]
